version: '3.8'
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://db:27017/mydatabase
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
